pipelines:
  demo:
    group: test
    label_template: ${COUNT}
    template: test-2
    materials:
        git: git@github.com:ananyasinha0125/iananya.git
        branch: main2
    stages:
    - deploy:
        approval:
          type: success
        jobs:
          deploy-job:
            timeout: 0
            tasks:
            - exec:
                command: ./build.sh
                run_if: passed                  
