format_version: 10

pipelines:
  ecs-nginx:
    environment_variables:
      env: demo
      docker_image:
      docker_tags:
    group: ecs-test
    label_template: "${COUNT}"
    template: ecs-test
    materials:
      repo:
        type: git
        url: git@github.com:ananyasinha0125/iananya.git
        branch: master
        destination: ecs-gocd

  ecs-httpd:
    environment_variables:
      env: httpd
      docker_image:
      docker_tags:
    group: ecs-test
    label_template: "${COUNT}"
    template: ecs-httpd
    materials:
      repo:
        type: git
        url: git@github.com:ananyasinha0125/iananya.git
        branch: master
        destination: ecs-gocd

