pipelines:
  ecs-demo:
    template: ecs-test 
    label_template: "${COUNT}"
    materials:
      repo:
        type: git
        url: git@github.com:ananyasinha0125/iananya.git
        branch: master
        destination: ecs-gocd
