format_version: 10

pipelines:
  ecs-nginx:
    environment_variables:
      env: nginx
      NGINX_IMAGE: "711387112611.dkr.ecr.us-east-1.amazonaws.com/nginx/app"
      NGINX_TAGS:
      AWS_ACCESS_KEY_ID:        
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: "us-east-1"
    group: ecs-test
    label_template: "${COUNT}"
    template: ecs-test
    materials:
      repo:
        type: git
        url: git@github.com:ananyasinha0125/iananya.git
        branch: master
        destination: ecs-gocd

  ecs-httpd:
    environment_variables:
      env: httpd
      HTTPD_IMAGE: "711387112611.dkr.ecr.us-east-1.amazonaws.com/httpd/app"
      HTTPD_TAGS: 
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_DEFAULT_REGION: "us-east-1"
    group: ecs-test
    label_template: "${COUNT}"
    template: ecs-test
    materials:
      repo:
        type: git
        url: git@github.com:ananyasinha0125/iananya.git
        branch: master
        destination: ecs-gocd


