format_version: 10

pipelines:
  ecs-demo:
    group: ecs-test         
    template: ecs-test     
    label_template: "${COUNT}"
    materials:
      repo:
        type: git
        url: git@github.com:ananyasinha0125/iananya.git
        branch: master
        destination: .
