format_version: 10

pipelines:
  ecs-demo:
    group: ecs-test            
    label_template: "${COUNT}"
    template: ecs-test
    materials:
      repo:
        type: git
        url: git@github.com:ananyasinha0125/iananya.git
        branch: master
        destination: ecs-gocd
