format_version: 10

pipelines:
  ecs-demo:
    group: ecs-test
    label_template: "${COUNT}"
    materials:
      repo:
        type: git
        url: git@github.com:ananyasinha0125/iananya.git
        branch: master
        destination: ecs-gocd
    stages:
     - deploy-ecs:
        jobs:
          deploy:
            timeout: 0
            environment_variables:
              VpcId: "vpc-0123456789abcdef0"
              PublicSubnetIds: "subnet-0a1b2c3d4e5f6g7h,subnet-1a2b3c4d5e6f7g8h"
              PrivateSubnetIds: "subnet-9a8b7c6d5e4f3g2h,subnet-7g6f5e4d3c2b1a0z"
              ClusterName: "test-cluster-ecs"
              ContainerImage: "711387112611.dkr.ecr.us-east-1.amazonaws.com/nginx/app:v1"
              ContainerPort: "80"
              InstanceType: "t3.medium"
              AmiId: "ami-0e1bed4f06a3b463d"
              DesiredCapacity: "2"
              MaxSize: "3"
              MinSize: "2"
              KeyName: "asg-nginx"
              AWS_ACCESS_KEY_ID: "AKIA2LIPZ4SRUZ37KWOJ"
              AWS_SECRET_ACCESS_KEY: "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"
              AWS_DEFAULT_REGION: "us-east-1" 
            tasks:
              - exec:
                  command: ls
                  arguments:
                    - -R
                    - .
              - exec:
                  command: chmod
                  arguments:
                    - +x
                    - ./ecs-gocd/ecs-gocd/scripts/deploy.sh
              - exec:
                  command: bash
                  arguments:
                    - ./ecs-gocd/ecs-gocd/scripts/deploy.sh
