format_version: 10

pipelines:
  ecs-demo:
    template: ecs-test
    group: ecs-test
    label_template: "${COUNT}"
    materials:
      repo:
        type: git
        url: git@github.com:ananyasinha0125/iananya.git
        branch: master
        destination: ecs-gocd
    stages:
      - deploy-ecs:
          jobs:
            deploy:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -R
                      - .
                - exec:
                    command: chmod
                    arguments:
                      - +x
                      - ./ecs-gocd/ecs-gocd/scripts/deploy.sh
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                          export AWS_PROFILE=ecs
                          bash ./ecs-gocd/ecs-gocd/scripts/deploy.sh
